# This is a basic workflow to help you get started with Actions

name: CI on brach Dev test NFY myc 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install dep for compilation and gsl
        run: sudo apt install build-essential libgsl-dev

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: g++ -o test -Wall $GITHUB_WORKSPACE/MocoLoco.cpp  -lgsl -lgslcblas
      
      - name: Run NFY test
        run: ls

        #      - name: hg38 genome download 
        #        run: cat get_hg38.script | bash
        #        working-directory: Genomes/hg38

      - name: hg19 genome download 
        run: cat get_hg19.script | bash
        working-directory: Genomes/hg19

      - name: mm10 genome download 
        run: cat get_mm10.script | bash
        working-directory: Genomes/mm10

      - name: Run NFY test
        run: ./test -b Test_Bed/nfy_k562_hg19.bed -t Genomes/hg19/hg19.2bit -j Jaspar_2020/MA0060.1.jaspar

      - name: Run myc test
        run: ./test -b Test_Bed/cMyc_hESC_mm10.bed -t Genomes/mm10/mm10.2bit -j Jaspar_2020/MA0147.2.jaspar
        
      - name: mv all artifax into testing
        run: 'mv *.txt testing/' 

      - uses: actions/upload-artifact@v2
        with:
          name: testing 
          path: testing
      

