# This is a basic workflow to help you get started with Actions

name: CI on brach Dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install build-essential

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: g++ -o test $GITHUB_WORKSPACE/*.cpp 
      
      - name: Run a multi-line script
        run: g++ -o test $GITHUB_WORKSPACE/*.cpp 
        
      - name: hg38 genome download 
        run: cat $GITHUB_WORKSPACE/Genomes/hg38/get_hg38.script | bash

      - name: hg19 genome download 
        run: cat $GITHUB_WORKSPACE/Genomes/hg19/get_hg19.script | bash

      - name: Run a multi-line script
        run: bash $GITHUB_WORKSPACE/test.sh output
      
      - name: Run a multi-line script
        run: cat $GITHUB_WORKSPACE/output
