# This is a basic workflow to help you get started with Actions

name: CI on brach Dev test NFY myc 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - reordering
      - table_creation_reorganization
  pull_request:
    branches: 
      - reordering
      - table_creation_reorganization
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install dep for compilation and gsl
        run: sudo apt install build-essential libgsl-dev

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: g++ -o MOCO -Wall $GITHUB_WORKSPACE/MocoLoco.cpp  -lgsl -lgslcblas

      - name: run simple test 
        run: ./MOCO -m Test_Bed/random_fasta.fasta -k 6 -d 1 -f 0.01
          
      - name: get sample test 
        run: wget https://gist.githubusercontent.com/AmarettiL/8e840cd1b90afa6d1fe32c77895121e2/raw/ba5d470ea8547abf79437a95bad1a98559fe22c9/Multifasta_test_result.txt
          
      - name: test difference between outputs 
        run: diff Multifasta_test_result.txt 6-mers_Z_scores_fasta_DS.txt

      - name: run kmer test
        run: ./MOCO -m Test_Bed/random_fasta.fasta -k 6,8,10 -d 1,2,3 -f 0.01

      - name: get kmer test
        run: |
              wget https://gist.githubusercontent.com/AmarettiL/4bc4ab52d4fae25fe5edb65ca951df2e/raw/4385ad8c1330d53c0f7bc5074c00775efede7d1d/6_mers_multi_test.txt && \
              wget https://gist.githubusercontent.com/AmarettiL/94e01af9459e8ddf99c625322ad5b98e/raw/8617ba2208831b6ba0da21f32678bbabb61117fe/8_mers_multi_test.txt && \
              wget https://gist.githubusercontent.com/AmarettiL/b718763712e5269fb9460ece74d6f75d/raw/cb66b6608d9407816802de91c529582693f5cff6/10_mers_multi_test.txt

      - name: test difference between outputs
        run: |
              diff 6_mers_multi_test.txt 6-mers_Z_scores_fasta_DS.txt && \
              diff 8_mers_multi_test.txt 8-mers_Z_scores_fasta_DS.txt && \
              diff 10_mers_multi_test.txt 10-mers_Z_scores_fasta_DS.txt

      - name: hg19 genome download 
        run: cat get_hg19.script | bash
        working-directory: Genomes/hg19

      - name: Run NFY test
        run: ./MOCO -b Test_Bed/nfy_k562_hg19.bed -j Jaspar_2020/MA0060.1.jaspar -t Genomes/hg19/hg19.2bit -p 150 -k 6 -d 1 -f 0.01
          
      - name: get sample test 
        run: wget https://gist.githubusercontent.com/AmarettiL/57ff3b08d8983a32de46f7cd3ae898a3/raw/006582b46c1b871d08ad7f3208e68d5664c4696d/NFY_bed_result.txt

      - name: test difference between outputs 
        run: diff NFY_bed_result.txt 6-mers_Z_scores_hg19.2bit_MA0060.1.jaspar_nfy_k562_hg19.bedDS.txt
      
      - name: Run EM test
        run: ./MOCO -b Test_Bed/nfy_k562_hg19.bed -j Jaspar_2020/MA0060.1.jaspar -t Genomes/hg19/hg19.2bit -p 150 -k 6,8 -d 1,2 -f 0.01 -e 100
          
      - name: get sample test 
        run: |
              wget https://gist.githubusercontent.com/AmarettiL/8b6737e9142edbf7660f6f8a941c107d/raw/069438fb27aa64f3bbd0c6f4073a66b9eaacb472/6_mers_EM_test.txt && \
              wget https://gist.githubusercontent.com/AmarettiL/7605ac3a241d9db15adf591d7f5a4a04/raw/b540e8343808589f597f00d556aeba1ce1102162/8_mers_EM_test.txt

      - name: test difference between outputs 
        run: |
              diff 6_mers_EM_test.txt 6-mers_Z_scores_fasta_DS.txt && \
              diff 8_mers_EM_test.txt 8-mers_Z_scores_fasta_DS.txt

        # Runs a set of commands using the runners shell
      - name: Compiling multifasta random tool
        run: g++ -o random_multifa -Wall $GITHUB_WORKSPACE/Random_multifa_TOOL/Multifa_random_tool.cpp
        
      

